name: track_env   # Name of the conda environment
channels:
  - conda-forge   # Priority channels for packages
  - bioconda      # Bioconda channel for bioinformatics tools
  - defaults

dependencies:
  # Core dependencies
  - python>=2.7       
  - snakemake         
  - pandas            
  - numpy                                      

  # Bioinformatics-specific dependencies
  - samtools          
  - bedtools
  - bedops
  - bcftools
  - vcftools      
  - emboss
  - trgt
  - ucsc-liftover
  - trf

  # R and related libraries
  - r-base            
  - r-tidyverse       
  - r-ggplot2        
  - r-dplyr           
  - r-vcfR            
  - r-hierfstat       
  - r-viridis        
  - r-tidyr                   
