fasta_path: "data/"
trf_run_script: "scripts/run_TRF.sh"
filter_catalog_script: "scripts/filter_tr_catalog.sh"
output_prefix: "homo"

# TRF configuration parameters
matchscore: 2
mismatchscore: 5
indelscore: 7
pm: 80
pi: 10
minscore: 24
maxperiod: 2000
