import glob
import os

configfile: "config.yaml"

# Rule to ensure all outputs are generated
rule all:
    input:
        f"{config['output_prefix']}_catalog.no_overlaps.bed"

rule run_trf_script:
    input:
        fasta_file=lambda wildcards: os.path.join(config["fasta_path"], f"{wildcards.prefix}.fa"),
        trf_run_script=config["trf_run_script"]
    output:
        os.path.join("trf_results", "{prefix}.fa.dat")
    shell:
        """
        bash {input.trf_run_script} -f {input.fasta_file}
        """

rule filter_catalog:
    input:
        expand("trf_results/{prefix}.fa.dat", prefix=[os.path.basename(f).replace('.fa', '') for f in glob.glob(os.path.join(config["fasta_path"], "*.fa"))])
    output:
        f"{config['output_prefix']}_catalog.no_overlaps.bed"
    params:
        filter_catalog_script=config["filter_catalog_script"],
        outfile=f"{config['output_prefix']}"
    shell:
        """
        bash {params.filter_catalog_script} trf_results/ {params.outfile}
        touch {output}
        """
